[package]
name = "mcr-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
mcr-jit.workspace = true
mcr-elf.workspace = true
mcr-sys.workspace = true
mcr-task.workspace = true
mcr-vfs.workspace = true
mcr-win.workspace = true

[dev-dependencies]
mcr-testkit.workspace = true

[lints]
workspace = true
